language: node_js
node_js:
  - "node"

# reporting to codecov. ends early because it can't login, so not particularly useful in this case.
intall:
  - npm install -g nyc
  - npm install -g codecov

before_script: chmod 0777 ./node_modules/.bin/mocha

script:
  - export TESTING="true"
  - npx nyc --reporter=lcov npm test && npx codecov

# this must be depricated because it can only properly review the code with the bot's token.
#### install:
#  - npm install -g codecov
#  - npm install -g istanbul
#script:
#  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
#  - codecov